server.port=8014
mybatis.mapper-locations=classpath:/mapper/*.xml


spring.datasource.url=jdbc:oracle:thin:@172.20.10.2:1521:xiaoatian

spring.datasource.username=tianbao

spring.datasource.password=tianbao

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
